import { ChargerStation, EVVehicleModel, FleetVehicle } from "./types";

export const VEHICLES_DATA: EVVehicleModel[] = [
  {
    id: "nexon-ev",
    name: "Nexon EV Max",
    brand: "Tata",
    batteryCapacityKwh: 40.5,
    estimatedRangeKm: 312,
    maxDcChargingRateKw: 50,
    chargingStandard: "CCS2"
  },
  {
    id: "mg-zs",
    name: "ZS EV",
    brand: "MG",
    batteryCapacityKwh: 50.3,
    estimatedRangeKm: 360,
    maxDcChargingRateKw: 75,
    chargingStandard: "CCS2"
  },
  {
    id: "byd-atto",
    name: "Atto 3",
    brand: "BYD",
    batteryCapacityKwh: 60.48,
    estimatedRangeKm: 420,
    maxDcChargingRateKw: 80,
    chargingStandard: "CCS2"
  },
  {
    id: "ioniq-5",
    name: "Ioniq 5",
    brand: "Hyundai",
    batteryCapacityKwh: 72.6,
    estimatedRangeKm: 480,
    maxDcChargingRateKw: 150,
    chargingStandard: "CCS2"
  },
  {
    id: "tiago-ev",
    name: "Tiago EV",
    brand: "Tata",
    batteryCapacityKwh: 24,
    estimatedRangeKm: 180,
    maxDcChargingRateKw: 25,
    chargingStandard: "CCS2"
  }
];

export const CHARGING_STATIONS_DATA: ChargerStation[] = [
  // DELHI NCR HUBS
  {
    id: "cp-tata-01",
    name: "Tata Power EZ Charge - Connaught Place Hub",
    operator: "Tata Power",
    city: "Delhi",
    latitude: 28.6304,
    longitude: 77.2177,
    totalConnectors: 6,
    availableConnectors: 2,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 60,
    pricingInrPerKwh: 18.5,
    queueLength: 1,
    avgWaitMins: 12,
    uptimeScore: 98.6,
    tempCelsius: 41,
    vibrationAnomalyScore: 0.12,
    amenities: ["Cafe Coffee Day", "Restroom", "AC Waiting Lounge"],
    ratings: 4.6,
    reviewsCount: 142
  },
  {
    id: "noida-statiq-02",
    name: "Statiq Charging Hub - Sector 62",
    operator: "Statiq",
    city: "Delhi",
    latitude: 28.6214,
    longitude: 77.3688,
    totalConnectors: 8,
    availableConnectors: 4,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 120,
    pricingInrPerKwh: 21.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 99.1,
    tempCelsius: 44,
    vibrationAnomalyScore: 0.05,
    amenities: ["Food Court", "Convenience Store", "Washroom"],
    ratings: 4.8,
    reviewsCount: 98
  },
  {
    id: "delhi-karol-bolt-01",
    name: "Bolt.Earth Core - Karol Bagh Market",
    operator: "Bolt.Earth",
    city: "Delhi",
    latitude: 28.6450,
    longitude: 77.1900,
    totalConnectors: 10,
    availableConnectors: 7,
    chargerType: "AC Type-2",
    powerOutputKw: 7.2,
    pricingInrPerKwh: 8.5,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 95.5,
    tempCelsius: 32,
    vibrationAnomalyScore: 0.1,
    amenities: ["Shopping Bazaar", "Street Food", "Tea Stall"],
    ratings: 4.3,
    reviewsCount: 88
  },
  {
    id: "delhi-gurgaon-cz-01",
    name: "ChargeZone Superfast - Cyber City DLF",
    operator: "ChargeZone",
    city: "Delhi",
    latitude: 28.4595,
    longitude: 77.0266,
    totalConnectors: 12,
    availableConnectors: 3,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 180,
    pricingInrPerKwh: 23.0,
    queueLength: 2,
    avgWaitMins: 15,
    uptimeScore: 98.1,
    tempCelsius: 49,
    vibrationAnomalyScore: 0.21,
    amenities: ["Starbucks", "ATM", "CyberHub Restrooms"],
    ratings: 4.7,
    reviewsCount: 312
  },
  {
    id: "delhi-dwarka-jiobp-01",
    name: "Jio-bp Pulse - Dwarka Sector 10 Hub",
    operator: "Jio-bp",
    city: "Delhi",
    latitude: 28.5850,
    longitude: 77.0500,
    totalConnectors: 8,
    availableConnectors: 1,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 100,
    pricingInrPerKwh: 19.8,
    queueLength: 3,
    avgWaitMins: 20,
    uptimeScore: 94.8,
    tempCelsius: 52,
    vibrationAnomalyScore: 0.45,
    amenities: ["Reliance Fresh", "Burger King", "Restrooms"],
    ratings: 4.2,
    reviewsCount: 159
  },
  {
    id: "delhi-saket-tata-02",
    name: "Tata Power EZ - Select Citywalk Mall",
    operator: "Tata Power",
    city: "Delhi",
    latitude: 28.5250,
    longitude: 77.2100,
    totalConnectors: 6,
    availableConnectors: 0,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 60,
    pricingInrPerKwh: 19.0,
    queueLength: 4,
    avgWaitMins: 28,
    uptimeScore: 97.2,
    tempCelsius: 46,
    vibrationAnomalyScore: 0.18,
    amenities: ["Mall Food Court", "Movie Theater", "Lounge"],
    ratings: 4.5,
    reviewsCount: 224
  },
  {
    id: "delhi-rohini-cz-02",
    name: "ChargeZone Lite - Rohini Sector 9",
    operator: "ChargeZone",
    city: "Delhi",
    latitude: 28.7050,
    longitude: 77.1150,
    totalConnectors: 4,
    availableConnectors: 2,
    chargerType: "AC Type-2",
    powerOutputKw: 22,
    pricingInrPerKwh: 10.5,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 92.4,
    tempCelsius: 38,
    vibrationAnomalyScore: 0.08,
    amenities: ["Metro Walk Mall", "Restroom"],
    ratings: 4.1,
    reviewsCount: 65
  },
  {
    id: "delhi-ghaziabad-jiobp-02",
    name: "Jio-bp Fast - Indirapuram Hub",
    operator: "Jio-bp",
    city: "Delhi",
    latitude: 28.6700,
    longitude: 77.4200,
    totalConnectors: 6,
    availableConnectors: 3,
    chargerType: "GB/T Fast",
    powerOutputKw: 50,
    pricingInrPerKwh: 16.5,
    queueLength: 1,
    avgWaitMins: 8,
    uptimeScore: 91.2,
    tempCelsius: 45,
    vibrationAnomalyScore: 0.35,
    amenities: ["Market Eateries", "Pharmacy", "Restroom"],
    ratings: 4.0,
    reviewsCount: 78
  },

  // MUMBAI HUBS
  {
    id: "bandra-jiobp-01",
    name: "Jio-bp Pulse Hub - Bandra Kurla Complex",
    operator: "Jio-bp",
    city: "Mumbai",
    latitude: 19.0596,
    longitude: 72.8295,
    totalConnectors: 10,
    availableConnectors: 1,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 120,
    pricingInrPerKwh: 19.5,
    queueLength: 3,
    avgWaitMins: 25,
    uptimeScore: 97.4,
    tempCelsius: 38,
    vibrationAnomalyScore: 0.45,
    amenities: ["Reliance Smart", "Pret A Manger", "Restroom"],
    ratings: 4.5,
    reviewsCount: 220
  },
  {
    id: "mumbai-colaba-tata-01",
    name: "Tata Power - Gateway Colaba Plaza",
    operator: "Tata Power",
    city: "Mumbai",
    latitude: 18.9150,
    longitude: 72.8250,
    totalConnectors: 4,
    availableConnectors: 3,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 50,
    pricingInrPerKwh: 18.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 99.4,
    tempCelsius: 34,
    vibrationAnomalyScore: 0.05,
    amenities: ["Taj Palace Lounges", "Cafe", "Ocean Walkway"],
    ratings: 4.9,
    reviewsCount: 180
  },
  {
    id: "mumbai-nariman-statiq-01",
    name: "Statiq Charger - Nariman Point Core",
    operator: "Statiq",
    city: "Mumbai",
    latitude: 18.9280,
    longitude: 72.8200,
    totalConnectors: 6,
    availableConnectors: 2,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 60,
    pricingInrPerKwh: 19.2,
    queueLength: 1,
    avgWaitMins: 10,
    uptimeScore: 96.8,
    tempCelsius: 39,
    vibrationAnomalyScore: 0.12,
    amenities: ["Corporate Food Courts", "ATM", "Sea View Bench"],
    ratings: 4.6,
    reviewsCount: 110
  },
  {
    id: "mumbai-dadar-cz-01",
    name: "ChargeZone Lite - Dadar TT Circle",
    operator: "ChargeZone",
    city: "Mumbai",
    latitude: 19.0178,
    longitude: 72.8478,
    totalConnectors: 8,
    availableConnectors: 3,
    chargerType: "AC Type-2",
    powerOutputKw: 22,
    pricingInrPerKwh: 10.0,
    queueLength: 1,
    avgWaitMins: 15,
    uptimeScore: 94.0,
    tempCelsius: 36,
    vibrationAnomalyScore: 0.15,
    amenities: ["Shopping Galleria", "Vegetarian Cafes", "Restroom"],
    ratings: 4.2,
    reviewsCount: 95
  },
  {
    id: "mumbai-worli-bolt-01",
    name: "Bolt.Earth Station - Worli Sea Face",
    operator: "Bolt.Earth",
    city: "Mumbai",
    latitude: 18.9980,
    longitude: 72.8150,
    totalConnectors: 6,
    availableConnectors: 4,
    chargerType: "AC Type-2",
    powerOutputKw: 7.2,
    pricingInrPerKwh: 9.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 98.7,
    tempCelsius: 33,
    vibrationAnomalyScore: 0.02,
    amenities: ["Sea View Cafe", "Public Promenade", "Charging Shelter"],
    ratings: 4.8,
    reviewsCount: 165
  },
  {
    id: "mumbai-chembur-tata-02",
    name: "Tata Power - Eastern Express Chembur",
    operator: "Tata Power",
    city: "Mumbai",
    latitude: 19.0620,
    longitude: 72.8980,
    totalConnectors: 8,
    availableConnectors: 5,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 120,
    pricingInrPerKwh: 20.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 98.9,
    tempCelsius: 40,
    vibrationAnomalyScore: 0.07,
    amenities: ["Highway Food Plaza", "Supermarket", "Fuel Station Restroom"],
    ratings: 4.5,
    reviewsCount: 137
  },
  {
    id: "mumbai-vashi-statiq-02",
    name: "Statiq Gigawatt - Vashi Sector 17",
    operator: "Statiq",
    city: "Mumbai",
    latitude: 19.0380,
    longitude: 72.9970,
    totalConnectors: 12,
    availableConnectors: 6,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 150,
    pricingInrPerKwh: 21.5,
    queueLength: 1,
    avgWaitMins: 8,
    uptimeScore: 97.6,
    tempCelsius: 42,
    vibrationAnomalyScore: 0.18,
    amenities: ["Mall Cafes", "Car Wash Service", "AC Lounge"],
    ratings: 4.7,
    reviewsCount: 228
  },

  // PUNE HUBS
  {
    id: "lonavala-cz-01",
    name: "ChargeZone Superfast - Highway Stop Lonavala",
    operator: "ChargeZone",
    city: "Pune",
    latitude: 18.7557,
    longitude: 73.4091,
    totalConnectors: 4,
    availableConnectors: 0,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 240,
    pricingInrPerKwh: 24.5,
    queueLength: 2,
    avgWaitMins: 15,
    uptimeScore: 92.5,
    tempCelsius: 58,
    vibrationAnomalyScore: 0.78,
    amenities: ["McDonalds", "Starbucks", "Fuel Pump Cafe", "Kids Park"],
    ratings: 4.2,
    reviewsCount: 310
  },
  {
    id: "pune-hinjewadi-bolt",
    name: "Bolt.Earth Micro Grid - Hinjewadi Tech Park",
    operator: "Bolt.Earth",
    city: "Pune",
    latitude: 18.5913,
    longitude: 73.7389,
    totalConnectors: 12,
    availableConnectors: 8,
    chargerType: "AC Type-2",
    powerOutputKw: 7.2,
    pricingInrPerKwh: 9.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 99.8,
    tempCelsius: 31,
    vibrationAnomalyScore: 0.01,
    amenities: ["IT Canteen", "Restroom", "Boba Shop"],
    ratings: 4.7,
    reviewsCount: 412
  },
  {
    id: "pune-shivajinagar-tata-01",
    name: "Tata Power - Shivajinagar Metro Station",
    operator: "Tata Power",
    city: "Pune",
    latitude: 18.5300,
    longitude: 73.8500,
    totalConnectors: 6,
    availableConnectors: 2,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 60,
    pricingInrPerKwh: 17.5,
    queueLength: 1,
    avgWaitMins: 8,
    uptimeScore: 99.1,
    tempCelsius: 37,
    vibrationAnomalyScore: 0.04,
    amenities: ["Metro Waiting Hall", "Snack Counters"],
    ratings: 4.6,
    reviewsCount: 194
  },
  {
    id: "pune-koregaon-statiq-01",
    name: "Statiq Charger - Koregaon Park Lane 1",
    operator: "Statiq",
    city: "Pune",
    latitude: 18.5360,
    longitude: 73.8930,
    totalConnectors: 8,
    availableConnectors: 3,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 80,
    pricingInrPerKwh: 19.5,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 96.5,
    tempCelsius: 39,
    vibrationAnomalyScore: 0.11,
    amenities: ["Organic Cafes", "Boutiques", "ATM"],
    ratings: 4.7,
    reviewsCount: 167
  },
  {
    id: "pune-kothrud-cz-01",
    name: "ChargeZone Lite - Kothrud DP Road",
    operator: "ChargeZone",
    city: "Pune",
    latitude: 18.5000,
    longitude: 73.8000,
    totalConnectors: 6,
    availableConnectors: 1,
    chargerType: "AC Type-2",
    powerOutputKw: 22,
    pricingInrPerKwh: 10.2,
    queueLength: 2,
    avgWaitMins: 18,
    uptimeScore: 94.2,
    tempCelsius: 35,
    vibrationAnomalyScore: 0.13,
    amenities: ["Saraswat Bank", "Tea Spot", "Restroom"],
    ratings: 4.3,
    reviewsCount: 89
  },
  {
    id: "pune-hadapsar-jiobp-01",
    name: "Jio-bp Pulse - Amanora Town Centre",
    operator: "Jio-bp",
    city: "Pune",
    latitude: 18.5000,
    longitude: 73.9200,
    totalConnectors: 10,
    availableConnectors: 0,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 120,
    pricingInrPerKwh: 20.5,
    queueLength: 3,
    avgWaitMins: 22,
    uptimeScore: 95.8,
    tempCelsius: 48,
    vibrationAnomalyScore: 0.38,
    amenities: ["Mall Food Court", "Hypermarket", "AC Waiting Room"],
    ratings: 4.4,
    reviewsCount: 215
  },

  // BENGALURU HUBS
  {
    id: "blr-indiranagar-tata",
    name: "Tata EZ Charge - Indiranagar Club Road",
    operator: "Tata Power",
    city: "Bengaluru",
    latitude: 12.9719,
    longitude: 77.6412,
    totalConnectors: 4,
    availableConnectors: 1,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 30,
    pricingInrPerKwh: 17.0,
    queueLength: 1,
    avgWaitMins: 10,
    uptimeScore: 96.2,
    tempCelsius: 35,
    vibrationAnomalyScore: 0.15,
    amenities: ["Indiranagar Market Cafes", "ATM", "Valet"],
    ratings: 4.4,
    reviewsCount: 189
  },
  {
    id: "blr-airport-statiq",
    name: "Statiq Megawatt Station - Kempegowda Intl Airport",
    operator: "Statiq",
    city: "Bengaluru",
    latitude: 13.1986,
    longitude: 77.7066,
    totalConnectors: 16,
    availableConnectors: 12,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 150,
    pricingInrPerKwh: 22.5,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 99.7,
    tempCelsius: 33,
    vibrationAnomalyScore: 0.02,
    amenities: ["Airport Lounge", "Subway", "Duty Free Store"],
    ratings: 4.9,
    reviewsCount: 540
  },
  {
    id: "blr-mgroad-cz-01",
    name: "ChargeZone Superfast - MG Road Metro Plaza",
    operator: "ChargeZone",
    city: "Bengaluru",
    latitude: 12.9745,
    longitude: 77.6110,
    totalConnectors: 10,
    availableConnectors: 5,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 180,
    pricingInrPerKwh: 21.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 98.4,
    tempCelsius: 37,
    vibrationAnomalyScore: 0.09,
    amenities: ["Metro Station Restroom", "Coffee Shop", "Retail Area"],
    ratings: 4.8,
    reviewsCount: 295
  },
  {
    id: "blr-koramangala-jiobp-01",
    name: "Jio-bp Pulse - Koramangala 80ft Road",
    operator: "Jio-bp",
    city: "Bengaluru",
    latitude: 12.9350,
    longitude: 77.6250,
    totalConnectors: 8,
    availableConnectors: 2,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 100,
    pricingInrPerKwh: 19.0,
    queueLength: 1,
    avgWaitMins: 12,
    uptimeScore: 95.9,
    tempCelsius: 41,
    vibrationAnomalyScore: 0.28,
    amenities: ["Burger King", "Supermarket", "Restrooms"],
    ratings: 4.5,
    reviewsCount: 198
  },
  {
    id: "blr-hsr-bolt-01",
    name: "Bolt.Earth Micro Grid - HSR Layout 27th Main",
    operator: "Bolt.Earth",
    city: "Bengaluru",
    latitude: 12.9100,
    longitude: 77.6400,
    totalConnectors: 12,
    availableConnectors: 9,
    chargerType: "AC Type-2",
    powerOutputKw: 7.2,
    pricingInrPerKwh: 8.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 99.2,
    tempCelsius: 30,
    vibrationAnomalyScore: 0.02,
    amenities: ["Park Walkway", "Eateries", "Restroom"],
    ratings: 4.6,
    reviewsCount: 312
  },
  {
    id: "blr-whitefield-tata-02",
    name: "Tata Power EZ - ITPL Whitefield",
    operator: "Tata Power",
    city: "Bengaluru",
    latitude: 12.9690,
    longitude: 77.7500,
    totalConnectors: 8,
    availableConnectors: 4,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 60,
    pricingInrPerKwh: 18.5,
    queueLength: 1,
    avgWaitMins: 9,
    uptimeScore: 97.5,
    tempCelsius: 38,
    vibrationAnomalyScore: 0.14,
    amenities: ["IT Food Court", "Lounge Wait Hub", "Car Repair Center"],
    ratings: 4.3,
    reviewsCount: 156
  },

  // CHENNAI HUBS
  {
    id: "chennai-omr-jiobp",
    name: "Jio-bp Pulse - OMR IT Expressway",
    operator: "Jio-bp",
    city: "Chennai",
    latitude: 12.9279,
    longitude: 80.2307,
    totalConnectors: 6,
    availableConnectors: 0,
    chargerType: "GB/T Fast",
    powerOutputKw: 50,
    pricingInrPerKwh: 16.0,
    queueLength: 4,
    avgWaitMins: 35,
    uptimeScore: 89.1,
    tempCelsius: 48,
    vibrationAnomalyScore: 0.89,
    amenities: ["Saravana Bhavan", "Restroom", "Shell Mart"],
    ratings: 3.9,
    reviewsCount: 74
  },
  {
    id: "chennai-beach-tata-01",
    name: "Tata Power - Marina Beach Core",
    operator: "Tata Power",
    city: "Chennai",
    latitude: 13.0800,
    longitude: 80.2750,
    totalConnectors: 6,
    availableConnectors: 3,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 60,
    pricingInrPerKwh: 17.5,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 98.4,
    tempCelsius: 43,
    vibrationAnomalyScore: 0.08,
    amenities: ["Beach Promenade", "Local Food Stalls", "ATM"],
    ratings: 4.5,
    reviewsCount: 142
  },
  {
    id: "chennai-tnagar-statiq-01",
    name: "Statiq Charging Hub - T-Nagar Shopping Central",
    operator: "Statiq",
    city: "Chennai",
    latitude: 13.0400,
    longitude: 80.2300,
    totalConnectors: 8,
    availableConnectors: 4,
    chargerType: "DC CCS2 Fast",
    powerOutputKw: 120,
    pricingInrPerKwh: 20.0,
    queueLength: 1,
    avgWaitMins: 10,
    uptimeScore: 97.9,
    tempCelsius: 46,
    vibrationAnomalyScore: 0.12,
    amenities: ["Silk Retailers", "Restrooms", "Snacks Corner"],
    ratings: 4.6,
    reviewsCount: 112
  },
  {
    id: "chennai-adyar-cz-01",
    name: "ChargeZone Lite - Adyar Flyover Plaza",
    operator: "ChargeZone",
    city: "Chennai",
    latitude: 13.0060,
    longitude: 80.2570,
    totalConnectors: 6,
    availableConnectors: 2,
    chargerType: "AC Type-2",
    powerOutputKw: 22,
    pricingInrPerKwh: 10.0,
    queueLength: 0,
    avgWaitMins: 0,
    uptimeScore: 94.6,
    tempCelsius: 42,
    vibrationAnomalyScore: 0.04,
    amenities: ["Bakery", "HDFC Bank ATM", "Washroom"],
    ratings: 4.4,
    reviewsCount: 63
  }
];

export const FLEET_VEHICLES_DATA: FleetVehicle[] = [
  {
    id: "F-ND-01",
    plateNumber: "DL 3C AB 4102",
    model: "Tata Ace EV (Cargo)",
    status: "Charging",
    soc: 45,
    rangeRemainingKm: 55,
    driverName: "Amit Kumar",
    todayCarbonOffsetKg: 34.2,
    todayChargingCostInr: 450
  },
  {
    id: "F-ND-02",
    plateNumber: "DL 1Y CA 9043",
    model: "Tata Nexon EV Max",
    status: "Transit",
    soc: 72,
    rangeRemainingKm: 225,
    driverName: "Rajesh Yadav",
    todayCarbonOffsetKg: 42.1,
    todayChargingCostInr: 680
  },
  {
    id: "F-MH-05",
    plateNumber: "MH 12 QX 5671",
    model: "BYD E6 (MPV Cab)",
    status: "Transit",
    soc: 85,
    rangeRemainingKm: 380,
    driverName: "Sandip Sawant",
    todayCarbonOffsetKg: 68.4,
    todayChargingCostInr: 920
  },
  {
    id: "F-BLR-12",
    plateNumber: "KA 03 MM 8890",
    model: "Mahindra Treo (3W)",
    status: "Idle",
    soc: 94,
    rangeRemainingKm: 112,
    driverName: "K. Reddy",
    todayCarbonOffsetKg: 18.5,
    todayChargingCostInr: 210
  },
  {
    id: "F-MH-14",
    plateNumber: "MH 14 TY 3310",
    model: "Tata Tigor EV",
    status: "Maintenance",
    soc: 18,
    rangeRemainingKm: 32,
    driverName: "Mahesh Deshmukh",
    todayCarbonOffsetKg: 0,
    todayChargingCostInr: 0
  },
  {
    id: "F-DL-09",
    plateNumber: "DL 2C AP 7733",
    model: "BYD Atto 3 (Premium Cargo)",
    status: "Charging",
    soc: 12,
    rangeRemainingKm: 50,
    driverName: "Vikram Jeet",
    todayCarbonOffsetKg: 54.8,
    todayChargingCostInr: 850
  }
];

export const ROUTE_PLANS = [
  {
    id: "mumbai-pune",
    name: "Mumbai to Pune Expressway",
    distanceKm: 150,
    source: "Mumbai (Gateway of India)",
    destination: "Pune (Koregaon Park)",
    baseEtaHours: 3.2,
    difficulty: "Moderate Elevation Climes (Western Ghats Sahyadri Hills)",
    stops: [
      {
        stationId: "lonavala-cz-01",
        name: "ChargeZone Superfast - Highway Stop Lonavala",
        kmMarker: 82,
        powerOutputKw: 240,
        tariffs: "₹24.5 / kWh",
        queueWaitTime: "15 mins",
        nearby: "McDonalds, Washrooms, Altitude Viewpoint"
      }
    ]
  },
  {
    id: "delhi-agra",
    name: "Delhi to Agra Yamuna Expressway",
    distanceKm: 230,
    source: "Delhi (Indira Gandhi T3)",
    destination: "Agra (Taj Mahal East Gate)",
    baseEtaHours: 4.1,
    difficulty: "High Thermal Impact (Uttar Pradesh plains summer breeze)",
    stops: [
      {
        stationId: "noida-statiq-02",
        name: "Statiq Charging Hub - Sector 62",
        kmMarker: 25,
        powerOutputKw: 120,
        tariffs: "₹21.0 / kWh",
        queueWaitTime: "0 mins",
        nearby: "Food Court, ATM, Airconditioned waiting lounge"
      }
    ]
  },
  {
    id: "blr-chennai",
    name: "Bengaluru to Chennai NH48 Expressway",
    distanceKm: 340,
    source: "Bengaluru (MG Road)",
    destination: "Chennai (Marina Beach)",
    baseEtaHours: 6.8,
    difficulty: "Extended Transit (Requires battery cooling cycle checks)",
    stops: [
      {
        stationId: "blr-airport-statiq",
        name: "Statiq Megawatt Station - Kempegowda",
        kmMarker: 30,
        powerOutputKw: 150,
        tariffs: "₹22.5 / kWh",
        queueWaitTime: "0 mins",
        nearby: "Airport Transit Lounge, Cafe"
      },
      {
        stationId: "chennai-omr-jiobp",
        name: "Jio-bp Pulse - OMR IT Expressway",
        kmMarker: 320,
        powerOutputKw: 50,
        tariffs: "₹16.0 / kWh",
        queueWaitTime: "35 mins",
        nearby: "Saravana Bhavan, Restrooms"
      }
    ]
  }
];
